/*
 * ================================================================
   RAXO All-mode PRO J2.5 - Template JS
 * ----------------------------------------------------------------
 * jQuery Layout Switch Plugin - v0.2
 * Copyright 2012 RAXO Group, Copyrighted Commercial Software
 * http://raxo.org
 * ================================================================
*/
(function(d){d.fn.layoutSwitch=function(g){function f(a,d){a.data("originalHeight",void 0==a.data("originalHeight")?a.height():a.data("originalHeight"));a.height(d)}function a(a){return void 0==a.data("originalHeight")?a.height():a.data("originalHeight")}function e(){var c=0,g=0,e=[];h.width(b.column_width).each(function(){var b=d(this),h=b.position().top;if(g!=h){for(currentDiv=0;currentDiv<e.length;currentDiv++)f(e[currentDiv],c);e.length=0;g=h;c=a(b);e.push(b)}else e.push(b),c=c<a(b)?a(b):c;for(currentDiv=0;currentDiv<e.length;currentDiv++)f(e[currentDiv],c)})}var b=d.extend({default_layout:"grid",column_width:"160",use_cookies:!0},g),g=d(this),c=g.find("div.allmode_itemsbox"),h=g.find("div.allmode_item"),j=g.find("div.allmode_switch span"),i=g.attr("id")+"_layout";return this.each(function(){b.default_layout=b.use_cookies&&d.cookie(i)?d.cookie(i):b.default_layout;"grid"==b.default_layout?e():(c.toggleClass("allmode_items_grid allmode_items_list"),j.toggleClass("active"));j.click(function(){if(d(this).is(".active")){j.toggleClass("active");if(d(this).is(".allmode_sw_grid")){c.fadeTo(200,0.1,function(){c.toggleClass("allmode_items_grid allmode_items_list").fadeTo(350,1);e()});b.use_cookies&&d.cookie(i,"grid",{expires:7})}else{c.fadeTo(200,0.1,function(){h.width("");c.toggleClass("allmode_items_grid allmode_items_list").fadeTo(350,1)});b.use_cookies&&d.cookie(i,"list",{expires:7})}}});d(window).resize(function(){c.is(".allmode_items_grid")&&e()})})}})(jQuery);
(function(d){d.cookie=function(g,f,a){if(1<arguments.length&&(!/Object/.test(Object.prototype.toString.call(f))||null===f||void 0===f)){a=d.extend({},a);if(null===f||void 0===f)a.expires=-1;if("number"===typeof a.expires){var e=a.expires,b=a.expires=new Date;b.setDate(b.getDate()+e)}f=""+f;return document.cookie=[encodeURIComponent(g),"=",a.raw?f:encodeURIComponent(f),a.expires?"; expires="+a.expires.toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.secure?"; secure":""].join("")}for(var a=f||{},e=a.raw?function(a){return a}:decodeURIComponent,b=document.cookie.split("; "),c=0,h;h=b[c]&&b[c].split("=");c++)if(e(h[0])===g)return e(h[1]||"");return null}})(jQuery);