name: _offline
timestamp: 1651774218
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1651774217
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-9259: Logo
  spacer:
    spacer-4978: Spacer
    spacer-7274: Spacer
  messages:
    system-messages-5331: 'System Messages'
  content:
    system-content-4696: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-9215: Copyright
  branding:
    branding-8516: Branding
inherit: {  }
