version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1651774217
layout:
  /header/:
    -
      - 'logo-9259 30'
      - 'spacer-4978 70'
  /main/:
    -
      - system-messages-5331
    -
      - system-content-4696
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9215 40'
      - 'spacer-7274 30'
      - 'branding-8516 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
