name: _body_only
timestamp: 1651774218
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1651774217
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-2073: 'System Messages'
  content:
    system-content-4456: 'Page Content'
inherit: {  }
