version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1651774217
layout:
  /header/:
    -
      - 'logo-5347 30'
      - 'spacer-9916 70'
  /navigation/:
    -
      - menu-4692
  /main/:
    -
      - system-content-1093
  /footer/:
    -
      - position-footer
    -
      - 'copyright-8143 40'
      - 'spacer-9455 30'
      - 'branding-2919 30'
  offcanvas:
    -
      - mobile-menu-8527
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
